### ISSUE TITLE
Crashing when opening Controls

### ISSUE THREAD

**Issue by Fortist** [SilentChaos512/WIT#1]
When I open the vanilla control GUI it instantly crashes.

http://pastebin.com/9jsYS39q

**Comment by Fortist** [comment]
I think it might be a forge thing, or a conflict with one of the few JEI mods I have, as I tried with the older version of this. Gonna downgrade forge a bit and try that

Though, I forgot to mention this only happens while In game, and not in the main menu.

**Comment by SilentChaos512** [comment]
I've seen this before (with and without WIT), I think it is a Forge issue. Best thing to do for now is set up controls before entering a world. Even after backing out of a world, it seems to crash most of the time.

**Comment by Fortist** [comment]
Thats very Inconvenient when setting up

**Comment by SilentChaos512** [comment]
Very true. Hopefully someone can track that bug down soon. The crash report is not very helpful though... Hard to tell what's going wrong.

**Comment by Fortist** [comment]
Hey, Im not the one who creates them. I just post them.
It shows whats installed and the set up.
Crashes when WIT is installed, doesnt crash when it's not
From looking at it, I'd say it a forge thing, hence why I said It might be a forge thing since it isnt instantly blaming WIT.

Maybe way later Ill try it again.

**Comment by SilentChaos512** [comment]
Apparently WIT was causing the crash. I've seen the same thing with other mods, so I made a bad assumption. It seems a half-complete key tracker can cause issues... Problem should be fixed in 1.0.3.

Sorry for the trouble!
