### ISSUE TITLE
[1.9.4] Problems with config file

### ISSUE THREAD

**Issue by MrAmericanMike** [SilentChaos512/WIT#11]
I'm having a problem with the Config file.

When I launch the pack for the first time, it gets created, then I modify everything to my taste. But after launching the pack again, the Config files changes everything to a new format.

Original file with my changes:
http://pastebin.com/8RGNfDMP

New modified file after 2nd launch:
http://pastebin.com/qvD4Y9JD

PS: Even after tweaking the 2nd file, all the changes are ignored and reset to defaults.

**Comment by SilentChaos512** [comment]
I'll look into that. I've always changed my settings through the Mods menu (on title screen, click Mods > select WIT > click Config). Try that and let me know if the changes are saved.
