### ISSUE TITLE
1.12 crashing on loading screen (bug)

### ISSUE THREAD

**Issue by Kzitold** [SilentChaos512/WIT#16]
Title says it all. The versions for MC 1.12 crashes in the middle of the loading screen.

https://pastebin.com/b2jYsPpm

**Comment by SilentChaos512** [comment]
And that's with nothing but WIT installed?

**Comment by Kzitold** [comment]
Yeah.
Want me to also try with a fresh directory?

**Comment by Kzitold** [comment]
Okay. Apparently, the old WIT.cfg (all caps) was preventing the new wit.cfg (no caps.)

**Comment by Kzitold** [comment]
Okay.
B:"Food Stats - Sneak Only"=false
and
B:"Tool Stats - Sneak Only"=false
breaks it.

**Comment by SilentChaos512** [comment]
Alright, I think I see the problem. I'll fix it when I get home from work.
