### ISSUE TITLE
1.10.2 crash with galacticraft

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/WIT#17]
There are crash with galacticraft when you try to choise a planet.

**Comment by SilentChaos512** [comment]
I need a crash report to know what's going wrong.

**Comment by ghost** [comment]
There aren't crash raport. Journey map have problem with same gui.

**Comment by SilentChaos512** [comment]
OK, could I see your log files then?

**Comment by KrauzeBartek** [comment]
Here you are 

[latest.log](https://github.com/SilentChaos512/WIT/files/1366487/latest.log)

**Comment by ghost** [comment]
[crash-2017-10-08_01.05.09-client.txt](https://github.com/SilentChaos512/WIT/files/1366505/crash-2017-10-08_01.05.09-client.txt)

**Comment by SilentChaos512** [comment]
Looks like Galacticraft's fault, but I should be able to catch the crash. Whatever their "EntityCelestialFake" is, it has a null display name.
