### ISSUE TITLE
ArrayOutOfBoundsException on module

### ISSUE THREAD

**Issue by GuusLieben** [SilentChaos512/WIT#18]
When using WIT and looking at specific items which don't seem to be related, other than the fact they're modded blocks, WIT outputs the proper information but also the following java error :

`java.lang.ArrayIndexOutOfBoundsException` 

As seen below (with no modules enabled)
![image](https://user-images.githubusercontent.com/10957963/32700981-1b4d6bd4-c7ce-11e7-9c54-511494f2d0ed.png)

Version info:
- Minecraft 1.10.2
- WIT 1.9.4-1.0.23-44

Other mods:
- ConquestReforged 2.1.3-mc1.10.2 (error occurs on blocks from this mod)
- OptiFine 1.10.2_HD_U_E3
- JourneyMap 1.10.2-5.4.5

**Comment by SilentChaos512** [comment]
Have a crash report or log files?

**Comment by GuusLieben** [comment]
It doesn't generate any (logged) errors, only the message displayed within the tooltip itself. Any debugging options I could follow to generate something?

**Comment by SilentChaos512** [comment]
I don't remember the 1.9/1.10 WIT code too well at this point, but this kind of error is typically the fault of the other mod. All I'm doing is asking the block for its name and catching the error the other mod generates.

**Comment by Zygus42** [comment]
WIT-1.12-1.0.25-44

I appear to have this same crash with a mod called Ferdinand's Flowers (but in 1.12.2):
[crash-2018-02-09_12.03.53-client.txt](https://github.com/SilentChaos512/WIT/files/1709740/crash-2018-02-09_12.03.53-client.txt)

Let me know if I should report it to them instead of yourself.
