### ISSUE TITLE
Crash w/ Plant Mega Pack

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/WIT#2]
Crash when looking at Plant Mega Pack Leaves.
Crash Log:
http://pastebin.com/2P8Wt8tT

**Comment by SilentChaos512** [comment]
Plant Mega Pack's fault. I _could_ add some error checking code, but it's probably best if I don't in this case.

Looks like a new version of PMP just released, try that out. I haven't crashed with that version.

Thanks for reporting.
