### ISSUE TITLE
[1.9] Client crash with Deep Resonance

### ISSUE THREAD

**Issue by dirtyfargo** [SilentChaos512/WIT#4]
Description: When I place down certain blocks from the 'Deep Resonance' mod with WIT installed, my client crashes with the report linked below :)
Crash Report: https://gist.github.com/dirtyfargo/59aa7610e9fa78685b1b
Forge Version:12.16.0.1804
Deep Resonance: 1.1.4beta18
WIT: 1.0.8-22

**Comment by SilentChaos512** [comment]
Looks like Deep Resonance is at fault, although I'm not an expert on the RF API. I'll go ahead and just disable the RF info, it doesn't work very well anyway.
