### ISSUE TITLE
[Crash]: Unexpected Error

### ISSUE THREAD

**Issue by Lanse505** [SilentChaos512/WIT#5]
Crashlog:
http://puu.sh/o3aes/08857fbb3f.txt

When did this occur?:
Randomly running around punching things in the world :P

**Comment by SilentChaos512** [comment]
Looks like the crash was caused by an inventory. Do you know what kind it was?

**Comment by Lanse505** [comment]
Nope, this happened when i simply turned around and looked at things in the world. I could jump in-game and see what i can find could have caused it.

**Comment by SilentChaos512** [comment]
I'll just add in a safety check. It looks like the fault of another mod, but that should at least prevent WIT from crashing. No guarantees about what will happen when the actual inventory is opened however...

**Comment by Lanse505** [comment]
Apparently it was a Grave from the Graves mod by Fireball1725
http://minecraft.curseforge.com/projects/graves?gameCategorySlug=mc-mods&projectID=240877
