### ISSUE TITLE
1.8.9-Crash w/ Buildcraft

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/WIT#6]
1.8.9-v1.0.7-19
Crashes when looking at buildcraft robots
Crash Log:
http://pastebin.com/decpLRrW

**Comment by SilentChaos512** [comment]
Seems Buildcraft robots return null for their display name... Somehow, I feel like that's bad practice, but I'll add in a safety check. I guess Buildcraft has it's reasons.

**Comment by WenXin20** [comment]
Thanks
